# GeoNetwor 

# Access via "http://localhost:8080/geonetwork" (or "http://$(docker-machine ip):8080/geonetwork" if using docker-machine)
#
# Default user: admin
# Default password: admin

version: '3.5'
services:

  geonetwork:
    image: geonetwork:3.10.0-postgres
    restart: unless-stopped
    container_name: core4geonetwork
    ports:
      - "8080:8080"
    environment:
      DATA_DIR: /var/lib/geonetwork_data
      POSTGRES_DB_HOST: db4geonetwork
      POSTGRES_DB_USERNAME: geonetwork
      POSTGRES_DB_PASSWORD: geonetwork
    depends_on:
      - postgres
    volumes:
      - geonetwork:/var/lib/geonetwork_data

# the db container
  postgres:
    image: mdillon/postgis
    restart: unless-stopped
    container_name: db4geonetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_USER: geonetwork
    volumes:
      - postgres:/var/lib/postgresql/data

# geoserver container
  geoserver:
    image: oscarfonts/geoserver
    container_name: geoserver4geonetwork
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      GEOSERVER_DATA_DIR: geonetwork
      GEOWEBCACHE_CACHE_DIR: geonetwork
    volumes:
      - geoserver:/opt/geoserver/data_dir
  mapstore:
    image: geosolutionsit/mapstore2:latest
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    volumes:
      - ./config:/etc/georchestra
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -Dgeorchestra.datadir=/etc/georchestra
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: on-failure:5
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: geonetwork
      MB_DB_PASS: geonetwork
      MB_DB_HOST: db4geonetwork
      MB_SITE_URL: http://localhost:3000/metabase/
      JAVA_TIMEZONE: America/Tegucigalpa

  nginx:
    image: nginx:stable
    ports:
      - 8083:8083
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"

volumes:
  geonetwork:
    name: data-geonetwork
  geoserver:
    name: data-geoserver
  postgres:
    name: data-postgres
